version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: libros_db
    restart: always
    environment:
      POSTGRES_USER: admin_libros
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: libreria_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: libros_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Usuario para entrar a la web
      PGADMIN_DEFAULT_PASSWORD: admin      # Clave para entrar a la web
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: